// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/contact-variants/ContactFirst.tsx": () => import("../components/mockups/contact-variants/ContactFirst.tsx"),
  "./components/mockups/contact-variants/DualPane.tsx": () => import("../components/mockups/contact-variants/DualPane.tsx"),
  "./components/mockups/contact-variants/FormCentric.tsx": () => import("../components/mockups/contact-variants/FormCentric.tsx")
};
